// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalPricesVaR(arg1:Array<number>,arg2:number):Promise<number>;

export function GetChartData(arg1:string,arg2:string,arg3:string):Promise<Array<any>>;

export function GetChartDataLabels(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetConsoleLogs():Promise<string>;

export function GetFundChartData(arg1:string,arg2:string,arg3:string):Promise<Array<any>>;

export function GetFundChartDataLabels(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetFundChartDataLastDaysLabels(arg1:string,arg2:number):Promise<Array<string>>;

export function GetFundChartLastDaysData(arg1:string,arg2:number):Promise<Array<any>>;

export function GetFundName(arg1:string):Promise<string>;

export function MaximumDrawdown(arg1:Array<number>):Promise<number>;

export function MovingAverageCrossover(arg1:Array<number>,arg2:number,arg3:number):Promise<Array<main.Signals>>;

export function MovingAverageCrossoverProfit(arg1:Array<number>,arg2:number,arg3:number):Promise<Array<main.DailyCash>>;

export function NormalDistribution(arg1:Array<number>):Promise<Array<main.Point>>;

export function SimpleMovingAverage(arg1:Array<number>,arg2:number):Promise<Array<number>>;

export function SyncFundHisData(arg1:string):Promise<void>;

export function SyncStockHisData(arg1:string,arg2:string):Promise<void>;
