// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChartData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetChartData'](arg1, arg2, arg3);
}

export function GetChartDataLabels(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetChartDataLabels'](arg1, arg2, arg3);
}

export function GetConsoleLogs() {
  return window['go']['main']['App']['GetConsoleLogs']();
}

export function SyncStockHisData(arg1, arg2) {
  return window['go']['main']['App']['SyncStockHisData'](arg1, arg2);
}
