// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChartData(arg1:string,arg2:string,arg3:string):Promise<Array<any>>;

export function GetChartDataLabels(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetConsoleLogs():Promise<string>;

export function SyncStockHisData(arg1:string,arg2:string):Promise<void>;
